steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/testing-deploy-fastapi:$COMMIT_SHA'
      - .
    id: Build Container Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/testing-deploy-fastapi:$COMMIT_SHA'
    id: Push Image to Container Registry
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - testing-deploy-fastapi
      - '--image'
      - 'gcr.io/$PROJECT_ID/testing-deploy-fastapi:$COMMIT_SHA'
      - '--region'
      - asia-southeast2
      - '--platform'
      - managed
    id: Deploy Container on Google Cloud Run
images:
  - 'gcr.io/$PROJECT_ID/testing-deploy-fastapi:$COMMIT_SHA'